deck = {1: {'name': 'The Fool', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        2: {'name': 'The Magician', 'arcana': 'major', 'suit': 'none', 'image': 'bike.png'},
        3: {'name': 'The High Priestess', 'arcana': 'major', 'suit': 'none', 'image': 'dark.png'},
        4: {'name': 'The Empress', 'arcana': 'major', 'suit': 'none', 'image': 'eclipse.png'},
        5: {'name': 'The Emperor', 'arcana': 'major', 'suit': 'none', 'image': 'orange.png'},
        6: {'name': 'The Hierophant', 'arcana': 'major', 'suit': 'none', 'image': 'wand.png'},
        7: {'name': 'The Lovers', 'arcana': 'major', 'suit': 'none', 'image': 'wand.png'},
        8: {'name': 'The Chariot', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        9: {'name': 'Strength', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        10: {'name': 'The Hermit', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        11: {'name': 'Wheel of Fortune', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        12: {'name': 'Justice', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        13: {'name': 'The Hanged Man', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        14: {'name': 'Death', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        15: {'name': 'Temperance', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        16: {'name': 'The Devil', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        17: {'name': 'The Tower', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        18: {'name': 'The Star', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        19: {'name': 'The Moon', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        20: {'name': 'The Sun', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        21: {'name': 'Judgement', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        22: {'name': 'The World', 'arcana': 'major', 'suit': 'none', 'image': 'axe.png'},
        23: {'name': 'Ace', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        24: {'name': 'Two', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        25: {'name': 'Three', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        26: {'name': 'Four', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        27: {'name': 'Five', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        28: {'name': 'Six', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        29: {'name': 'Seven', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        30: {'name': 'Eight', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        31: {'name': 'Nine', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        32: {'name': 'Ten', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        33: {'name': 'Page', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        34: {'name': 'Knight', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        35: {'name': 'Queen', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        36: {'name': 'King', 'arcana': 'minor', 'suit': 'Cups', 'image': 'woman.png'},
        37: {'name': 'Ace', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        38: {'name': 'Two', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        39: {'name': 'Three', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        40: {'name': 'Four', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        41: {'name': 'Five', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        42: {'name': 'Six', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        43: {'name': 'Seven', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        44: {'name': 'Eight', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        45: {'name': 'Nine', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        46: {'name': 'Ten', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        47: {'name': 'Page', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        48: {'name': 'Knight', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        49: {'name': 'Queen', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        50: {'name': 'King', 'arcana': 'minor', 'suit': 'Swords', 'image': 'orange.png'},
        51: {'name': 'Ace', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        52: {'name': 'Two', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        53: {'name': 'Three', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        54: {'name': 'Four', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        55: {'name': 'Five', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        56: {'name': 'Six', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        57: {'name': 'Seven', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        58: {'name': 'Eight', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        59: {'name': 'Nine', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        60: {'name': 'Ten', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        61: {'name': 'Page', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        62: {'name': 'Knight', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        63: {'name': 'Queen', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        64: {'name': 'King', 'arcana': 'minor', 'suit': 'Pentacles', 'image': 'bike.png'},
        65: {'name': 'Ace', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        66: {'name': 'Two', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        67: {'name': 'Three', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        68: {'name': 'Four', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        69: {'name': 'Five', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        70: {'name': 'Six', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        71: {'name': 'Seven', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        72: {'name': 'Eight', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        73: {'name': 'Nine', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        74: {'name': 'Ten', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        75: {'name': 'Page', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        76: {'name': 'Knight', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        77: {'name': 'Queen', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'},
        78: {'name': 'King', 'arcana': 'minor', 'suit': 'Wands', 'image': 'axe.png'}}